### ISSUE TITLE
Error: Invalid configuration when using Sampler()

### ISSUE THREAD

**Issue by kezmcd1903** [dwavesystems/dwave-ocean-sdk#291] opened 2024-04-08 14:47 UTC
**Description**
After authenticating and configuring dwave access in a virtual environment, checking that access to Leap works -

`dwave ping`,

I get the error:

`TypeError: __init__() got an unexpected keyword argument 'other'`

**To Reproduce**
Here's my code to reproduce:

```import networkx as nx
import dwave_networkx as dnx
from dwave.system import DWaveSampler, EmbeddingComposite
s5 = nx.star_graph(4)  # a star graph where node 0 is hub to four other nodes
sampler = EmbeddingComposite(DWaveSampler())
print(dnx.min_vertex_cover(s5, sampler))
```

Full error:

```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 5
      3 from dwave.system import DWaveSampler, EmbeddingComposite
      4 s5 = nx.star_graph(4)  # a star graph where node 0 is hub to four other nodes
----> 5 sampler = EmbeddingComposite(DWaveSampler())
      6 print(dnx.min_vertex_cover(s5, sampler))

File ~/.local/lib/python3.8/site-packages/dwave/system/samplers/dwave_sampler.py:183, in DWaveSampler.__init__(self, failover, retry_interval, **config)
    180 self.retry_interval = retry_interval
    181 self._solver_penalty = defaultdict(int)
--> 183 self.client = Client.from_config(**config)
    184 self.solver = self._get_solver(penalty=self._solver_penalty)

File ~/.local/lib/python3.8/site-packages/dwave/cloud/client/base.py:430, in Client.from_config(cls, config_file, profile, client, **kwargs)
    427 _client = config.pop('client', None) or 'base'
    429 logger.debug("Creating %s.Client() with: %r", _client, config)
--> 430 return _clients[_client](**config)

File ~/.local/lib/python3.8/site-packages/dwave/cloud/events.py:105, in dispatches_events.__call__.<locals>.wrapped(*pargs, **kwargs)
    103 dispatch_event(self.before_eventname, obj=obj, args=args)
    104 try:
--> 105     rval = fn(*pargs, **kwargs)
    106 except Exception as exc:
    107     dispatch_event(self.after_eventname, obj=obj, args=args, exception=exc)

File ~/.local/lib/python3.8/site-packages/dwave/cloud/client/base.py:491, in Client.__init__(self, *args, **kwargs)
    488     raise ValueError("API token not defined")
    490 # Create session for main thread only
--> 491 self.session = self.create_session()
    493 # Build the problem submission queue, start its workers
    494 self._submission_queue = queue.Queue()

File ~/.local/lib/python3.8/site-packages/dwave/cloud/client/base.py:554, in Client.create_session(self)
    549     endpoint += '/'
    551 session = BaseUrlSession(base_url=endpoint)
    552 session.mount('htt[p://](file:///P://)', PretimedHTTPAdapter(
    553     timeout=self.config.request_timeout,
--> 554     max_retries=self.config.request_retry.to_urllib3_retry()))
    555 session.mount('http[s://](file:///S://)', PretimedHTTPAdapter(
    556     timeout=self.config.request_timeout,
    557     max_retries=self.config.request_retry.to_urllib3_retry()))
    559 session.headers.update({'User-Agent': default_user_agent()})

File ~/.local/lib/python3.8/site-packages/dwave/cloud/config/models.py:81, in RequestRetryConfig.to_urllib3_retry(self)
     78 # `urllib3<2` doesn't support `backoff_max` in `Retry()`
     79 del params['backoff_max']
---> 81 retry = urllib3.Retry(**params)
     83 if self.backoff_max is not None:
     84     # handle `urllib3>=1.21.1,<1.27` AND `urllib3>=1.21.1,<3`
     85     retry.BACKOFF_MAX = retry.backoff_max = self.backoff_max

TypeError: __init__() got an unexpected keyword argument 'other'```



**Environment:**
 - OS: [Linux]

**Comment by randomir** [comment] 2024-04-08 15:06
Hi @kezmcd1903, this looks like a bug we recently fixed in https://github.com/dwavesystems/dwave-cloud-client/pull/612. The reason are too loose requirements over `urllib3`, possibly conflicting with pip requirements in your (virtual)environment. The fix is scheduled to be released with the next version of Ocean, sometime early next week.

Until then, to verify/fix, please run:
```
pip install -U 'urllib3>=1.26,<3'
```

and try running `dwave ping` again.

**Comment by kezmcd1903** [comment] 2024-04-08 15:36
Hi @randomir, thanks for your reply. I already had:

`Requirement already satisfied: urllib3<3,>=1.26 in ./env_dwave/lib/python3.8/site-packages (2.2.1)`

dwave ping is working fine. It is when I use the sampler that the problem occurs:

`sampler = EmbeddingComposite(DWaveSampler())`

**Comment by randomir** [comment] 2024-04-08 15:40
Looks like you're running `dwave` from one venv (`./env_dwave/lib/python3.8/`), and your python script from another venv (`~/.local/lib/python3.8`)?

**Comment by randomir** [comment] 2024-04-17 15:03
The initial error here was caused by a bug resolved in https://github.com/dwavesystems/dwave-cloud-client/pull/612.

**Closed by randomir** 2024-04-17 15:03 UTC
